package com.example.zhoukao3_moni.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhoukao3_moni.bean.NewsResult;

import com.example.zhoukao3_moni.dao.NewsResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsResultDaoConfig;

    private final NewsResultDao newsResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsResultDaoConfig = daoConfigMap.get(NewsResultDao.class).clone();
        newsResultDaoConfig.initIdentityScope(type);

        newsResultDao = new NewsResultDao(newsResultDaoConfig, this);

        registerDao(NewsResult.class, newsResultDao);
    }
    
    public void clear() {
        newsResultDaoConfig.clearIdentityScope();
    }

    public NewsResultDao getNewsResultDao() {
        return newsResultDao;
    }

}
